In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

**Creating, Reading, and Writing**

In [2]:
df1 = pd.DataFrame({'Apples': [35, 41],
                        'Bananas': [21, 34],
                    },
                        index=['2017 Sales', '2018 Sales'])

In [3]:
df1

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [4]:
my_list = ['4 cups', '1 cup', '2 large', '1 can']
ind = ['Flour', 'Milk', 'Eggs', 'Spam']

pd.Series(data=my_list,index=ind)

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
dtype: object

In [5]:
# Suppose we have the following dataframe:
#q6_df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
#save this to a CSV file

q6_df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
q6_df.to_csv('q6_df',index=False)

Indexing, Selecting, and Assigning

In [6]:
reviews = pd.read_csv('winemag_data.csv')

In [7]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [8]:
del reviews['Unnamed: 0']

In [9]:
reviews['description'][0]

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [10]:
reviews.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [11]:
#select first 10 values from description series

reviews['description'][0:9]

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
Name: description, dtype: object

In [12]:
#Select the `country`, `province`, `region_1`, and `region_2` columns with `0`, `1`, `10`, and `100` index positions. 

reviews.loc[[0,1,10,100], ['country', 'province', 'region_1', 'region_2']]

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

In [13]:
#select country and variety of first 100 records

reviews.loc[1:100, ['country', 'variety']].head()

    country             variety
1  Portugal      Portuguese Red
2        US          Pinot Gris
3        US            Riesling
4        US          Pinot Noir
5     Spain  Tempranillo-Merlot

In [14]:
#select wines made in Italy

reviews[reviews['country'] == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
26,Italy,Pretty aromas of yellow flower and stone fruit...,Dalila,87,13.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Stemmari 2013 Dalila White (Terre Siciliane),White Blend,Stemmari
27,Italy,"Aromas recall ripe dark berry, toast and a whi...",NaN,87,10.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Stemmari 2013 Nero d'Avola (Terre Siciliane),Nero d'Avola,Stemmari
28,Italy,"Aromas suggest mature berry, scorched earth, a...",Mascaria Barricato,87,17.0,Sicily & Sardinia,Cerasuolo di Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2011 Mascaria Barricato (Cera...,Red Blend,Terre di Giurfo
31,Italy,Merlot and Nero d'Avola form the base for this...,Calanìca Nero d'Avola-Merlot,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2010 Calanìca Nero d'Avola-...,Red Blend,Duca di Salaparuta
32,Italy,"Part of the extended Calanìca series, this Gri...",Calanìca Grillo-Viognier,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Duca di Salaparuta 2011 Calanìca Grillo-Viogni...,White Blend,Duca di Salaparuta
37,Italy,This concentrated Cabernet offers aromas of cu...,Missoni,86,21.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Feudi del Pisciotto 2010 Missoni Cabernet Sauv...,Cabernet Sauvignon,Feudi del Pisciotto
38,Italy,"Inky in color, this wine has plump aromas of r...",I Tratturi,86,11.0,Southern Italy,Puglia,NaN,NaN,NaN,Feudi di San Marzano 2011 I Tratturi Primitivo...,Primitivo,Feudi di San Marzano
39,Italy,"Part of the natural wine movement, this wine i...",Purato Made With Organic Grapes,86,12.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Feudo di Santa Tresa 2011 Purato Made With Org...,Nero d'Avola,Feudo di Santa Tresa
40,Italy,Catarratto is one of Sicily's most widely farm...,NaN,86,17.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Feudo Montoni 2011 Catarratto (Sicilia),Catarratto,Feudo Montoni
46,Italy,"Spicy, fresh and clean, this would pair with f...",Sallier de la Tour,86,13.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Tasca d'Almerita 2011 Sallier de la Tour Inzol...,Inzolia,Tasca d'Almerita
50,Italy,This blend of Nero d'Avola and Syrah opens wit...,Scialo,86,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Viticultori Associati Canicatti 2008 Scialo Re...,Red Blend,Viticultori Associati Canicatti
52,Italy,The Monica grape often shows a rustic or raw q...,Dolia,85,14.0,Sicily & Sardinia,Monica di Sardegna,NaN,NaN,NaN,Cantine di Dolianova 2010 Dolia (Monica di Sa...,Monica,Cantine di Dolianova
54,Italy,"A blend of Nero d'Avola and Nerello Mascalese,...",Rosso,85,NaN,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Corvo 2010 Rosso Red (Sicilia),Red Blend,Corvo
57,Italy,There's a touch of toasted almond at the start...,Sallier de la Tour,85,13.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,Tasca d'Almerita 2011 Sallier de la Tour Grill...,Grillo,Tasca d'Almerita
61,Italy,This densely hued wine has aromas of black plu...,Prugneto,86,17.0,Central Italy,Romagna,NaN,Kerin O’Keefe,@kerinokeefe,Podere dal Nespoli 2015 Prugneto Sangiovese (R...,Sangiovese,Podere dal Nespoli
72,Italy,"Aromas of black-skinned fruit, leather, underb...",Daginestra,86,32.0,Southern Italy,Aglianico del Vulture,NaN,Kerin O’Keefe,@kerinokeefe,Grifalco 2013 Daginestra (Aglianico del Vulture),Aglianico,Grifalco
88,Italy,"Subdued aromas of French oak, toast and acacia...",Le Mandorle Riserva,86,29.0,Tuscany,Vernaccia di San Gimignano,NaN,Kerin O’Keefe,@kerinokeefe,Poggio Alloro 2014 Le Mandorle Riserva (Verna...,Vernaccia,Poggio Alloro
89,Italy,"Made primarily from Sangiovese, with some Malv...",NaN,88,19.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Fattoria Sardi 2015 Rosato (Toscana),Rosato,Fattoria Sardi
98,Italy,"Forest floor, menthol, espresso, cranberry and...",Dono Riserva,88,30.0,Tuscany,Morellino di Scansano,NaN,Kerin O’Keefe,@kerinokeefe,Serpaia di Endrizzi 2010 Dono Riserva (Morell...,Sangiovese,Serpaia di Endrizzi
104,Italy,"Made with 65% Sangiovese, 20% Merlot and 15% C...",Nativo,87,16.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Madonna Alta 2014 Nativo Red (Toscana),Red Blend,Madonna Alta
105,Italy,Made predominantly with Trebbiano and Malvasia...,Villa Antinori,87,14.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Marchesi Antinori 2015 Villa Antinori White (T...,White Blend,Marchesi Antinori
106,Italy,"A blend of Cabernet Sauvignon, Merlot, Caberne...",Castiglioni,87,30.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Marchesi de' Frescobaldi 2014 Castiglioni Red ...,Red Blend,Marchesi de' Frescobaldi
107,Italy,"Aromas of yellow stone fruit, white spring flo...",Ammiraglia Massovivo,87,18.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Marchesi de' Frescobaldi 2015 Ammiraglia Masso...,Vermentino,Marchesi de' Frescobaldi
109,Italy,"An easy-drinking blend of Merlot, Sangiovese a...",Le Volte,87,30.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Ornellaia 2014 Le Volte Red (Toscana),Red Blend,Ornellaia
112,Italy,"Made with 90% Merlot and 10% Alicante, this ea...",Semifonte,87,15.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Podere Ciona 2014 Semifonte Red (Toscana),Red Blend,Podere Ciona
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129740,Italy,"Blackberry, underbrush and cooking spice aroma...",Il Costone Riserva,90,45.0,Central Italy,Romagna,NaN,Kerin O’Keefe,@kerinokeefe,Braschi 2013 Il Costone Riserva Sangiovese (Ro...,Sangiovese,Braschi
129750,Italy,"Made from organically grown grapes, this brigh...",NaN,87,18.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Di Giovanna 2013 Grillo (Terre Siciliane),Grillo,Di Giovanna
129760,Italy,An alluring fragrance of orange blossom and ma...,Kràtos,87,25.0,Southern Italy,Paestum,NaN,Kerin O’Keefe,@kerinokeefe,Luigi Maffini 2012 Kràtos Fiano (Paestum),Fiano,Luigi Maffini
129778,Italy,"Despite its high alcohol, this is surprisingly...",Di Carlo,89,80.0,Veneto,Amarone della Valpolicella Classico,NaN,NaN,NaN,Cantine Lenotti di Lenotti 2007 Di Carlo (Ama...,"Corvina, Rondinella, Molinara",Cantine Lenotti di Lenotti
129795,Italy,This bold offering shows jammy fruit aromas of...,NaN,88,55.0,Veneto,Amarone della Valpolicella Classico,NaN,NaN,NaN,Le Ragose 2005 Amarone della Valpolicella Cla...,"Corvina, Rondinella, Molinara",Le Ragose
129797,Italy,This would pair perfectly with the sweet and s...,NaN,88,26.0,Veneto,Valpolicella Classico Superiore Ripasso,NaN,NaN,NaN,Arduini 2010 Valpolicella Classico Superiore ...,"Corvina, Rondinella, Molinara",Arduini
129801,Italy,"“Il Bugiardo,” which is Italian for “the liar,...",Il Bugiardo,88,36.0,Veneto,Valpolicella Classico Superiore Ripasso,NaN,NaN,NaN,Buglioni 2009 Il Bugiardo (Valpolicella Class...,"Corvina, Rondinella, Molinara",Buglioni
129803,Italy,"Produced by vintner Fernando Campagnola, this ...",Gli Archi,88,50.0,Veneto,Amarone della Valpolicella Classico,NaN,NaN,NaN,Corte Archi 2008 Gli Archi (Amarone della Val...,"Corvina, Rondinella, Molinara",Corte Archi
129804,Italy,"Having endured up to 8 months of oak aging, th...",Podere Bertarole,88,25.0,Veneto,Valpolicella Classico Superiore Ripasso,NaN,NaN,NaN,Corteforte 2009 Podere Bertarole (Valpolicell...,"Corvina, Rondinella, Molinara",Corteforte
129807,Italy,Here is yet another Roero Riserva from the suc...,Roche d'Ampsej Riserva,89,NaN,Piedmont,Roero,NaN,NaN,NaN,Matteo Correggia 2007 Roche d'Ampsej Riserva ...,Nebbiolo,Matteo Correggia
129809,Italy,This pretty Riserva Nebbiolo will surely grow ...,Fausone Riserva,89,62.0,Piedmont,Barbaresco,NaN,NaN,NaN,Prinsi 2006 Fausone Riserva (Barbaresco),Nebbiolo,Prinsi
129813,Italy,Here's a more informal and approachable expres...,Chirlet,89,NaN,Piedmont,Barolo,NaN,NaN,NaN,Simone Scaletta 2007 Chirlet (Barolo),Nebbiolo,Simone Scaletta
129819,Italy,Barbaresco NonnOrlando delivers clean and subt...,NonnOrlando,89,75.0,Piedmont,Barbaresco,NaN,NaN,NaN,Vigin 2008 NonnOrlando (Barbaresco),Nebbiolo,Vigin
129822,Italy,"This lovely base Barbaresco exhibits a soft, g...",NaN,89,45.0,Piedmont,Barbaresco,NaN,NaN,NaN,Ca' du Rabajà 2008 Barbaresco,Nebbiolo,Ca' du Rabajà
129824,Italy,The 2006 vintage is a tricky one for Barolo be...,NaN,89,85.0,Piedmont,Barolo,NaN,NaN,NaN,Coppo 2006 Barolo,Nebbiolo,Coppo
129826,Italy,Barolo Cantina Tre Serre is a taut and well de...,Cantina Tre Serre,88,50.0,Piedmont,Barolo,NaN,NaN,NaN,Vinchio-Vaglio Serra 2006 Cantina Tre Serre (...,Nebbiolo,Vinchio-Vaglio Serra
129842,Italy,This mature Primitivo from the Salento area of...,NaN,86,12.0,Southern Italy,Salento,NaN,NaN,NaN,Cantele 2006 Primitivo (Salento),Primitivo,Cantele
129843,Italy,This is a very pretty expression of Vermentino...,Etichetta Grigia,86,18.0,Northwestern Italy,Colli di Luni,NaN,NaN,NaN,Cantine Lunae Bosoni 2006 Etichetta Grigia Ver...,Vermentino,Cantine Lunae Bosoni
129844,Italy,"Doga delle Clavule is a neutral, mineral-drive...",Doga delle Clavule,86,NaN,Tuscany,Morellino di Scansano,NaN,NaN,NaN,Caparzo 2006 Doga delle Clavule (Morellino di...,Sangiovese,Caparzo
129849,Italy,This 100% expression of Corvina offers pointed...,Vignenuove,86,20.0,Veneto,Veneto,NaN,NaN,NaN,Luciana Cordioli 2006 Vignenuove Corvina (Veneto),Corvina,Luciana Cordioli
129850,Italy,Here's an Aglianico from Campania with bright ...,NaN,86,24.0,Southern Italy,Campania,NaN,NaN,NaN,Macchialupa 2006 Aglianico (Campania),Aglianico,Macchialupa
129851,Italy,Almond paste and crushed pistachio nut charact...,NaN,86,10.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,MandraRossa 2006 Nero d'Avola (Sicilia),Nero d'Avola,MandraRossa
129852,Italy,Here's an easy blend of Cabernet Sauvignon and...,NaN,86,10.0,Sicily & Sardinia,Sicilia,NaN,NaN,NaN,MandraRossa 2006 Cabernet Sauvignon-Shiraz (Si...,Cabernet Sauvignon-Shiraz,MandraRossa
129892,Italy,"Classic Sangiovese aromas of red berry, culina...",NaN,91,72.0,Tuscany,Brunello di Montalcino,NaN,Kerin O’Keefe,@kerinokeefe,La Mannella 2012 Brunello di Montalcino,Sangiovese,La Mannella
129893,Italy,"Aromas of passion fruit, hay and a vegetal not...",Corte Menini,91,NaN,Veneto,Soave Classico,NaN,Kerin O’Keefe,@kerinokeefe,Le Mandolare 2015 Corte Menini (Soave Classico),Garganega,Le Mandolare
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [15]:
#Select wines whose region_2 is not NaN.

review2 = reviews.dropna(subset=['region_2'])
review2['region_2'].head()

2     Willamette Valley
4     Willamette Valley
10                 Napa
12               Sonoma
14        Central Coast
Name: region_2, dtype: object

In [16]:
#select points column for the last 1000 wines

reviews['points'][-1000:]

128971    91
128972    91
128973    91
128974    91
128975    91
128976    91
128977    91
128978    91
128979    91
128980    93
128981    93
128982    93
128983    93
128984    93
128985    93
128986    93
128987    93
128988    93
128989    93
128990    93
128991    93
128992    93
128993    93
128994    93
128995    93
128996    93
128997    93
128998    93
128999    93
129000    93
          ..
129941    90
129942    90
129943    90
129944    90
129945    90
129946    90
129947    90
129948    90
129949    90
129950    90
129951    90
129952    90
129953    90
129954    90
129955    90
129956    90
129957    90
129958    90
129959    90
129960    90
129961    90
129962    90
129963    90
129964    90
129965    90
129966    90
129967    90
129968    90
129969    90
129970    90
Name: points, Length: 1000, dtype: int64

In [17]:
#Select the `points` column, but only for wines made in Italy.

reviews[reviews['country'] == 'Italy']['points']

0         87
6         87
13        87
22        87
24        87
26        87
27        87
28        87
31        86
32        86
37        86
38        86
39        86
40        86
46        86
50        86
52        85
54        85
57        85
61        86
72        86
88        86
89        88
98        88
104       87
105       87
106       87
107       87
109       87
112       87
          ..
129740    90
129750    87
129760    87
129778    89
129795    88
129797    88
129801    88
129803    88
129804    88
129807    89
129809    89
129813    89
129819    89
129822    89
129824    89
129826    88
129842    86
129843    86
129844    86
129849    86
129850    86
129851    86
129852    86
129892    91
129893    91
129929    91
129943    90
129947    90
129961    90
129962    90
Name: points, Length: 19540, dtype: int64

In [18]:
#Who produces more above-averagely good wines, France or Italy? 
#Select the `country` column, but only  when said `country` is one of those two options, 
#and the `points` column is greater than or equal to 90.

first_df = reviews[(reviews['country'] =='France') | (reviews['country'] =='Italy')]

second_df = first_df[(first_df['points'] >= 90)]

second_df['country'].head()

119    France
120     Italy
126    France
127    France
128    France
Name: country, dtype: object

**Summary Functions and Maps**

In [19]:
#What is the median of the 'points' column?

reviews['points'].median()

88.0

In [20]:
#What countries appear in the dataset most often?

reviews['country'].value_counts()

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Macedonia                    12
Serbia                       12
Czech Republic               12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
China                         1
Slovakia                      1
Egypt                         1
Name: country, dtype: int64

In [21]:
#subtract median price from price in new df

med = reviews['price'].median()

reviews_2 = reviews.copy()
reviews_2['price'] = reviews['price'].apply(lambda x: x - med)
reviews_2.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,-10.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,-11.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,-12.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,40.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [22]:
#which wine has the highest points-to-price ratio in the dataset?

reviews_3 = reviews[pd.notnull(reviews['points'])]
reviews_3 = reviews[pd.notnull(reviews['price'])]

reviews_3['ratio'] = reviews_3['points'] / reviews_3['price']

reviews_3.sort_values('ratio', ascending = False).head()

/Users/shaynahowitt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,ratio
64590,US,"There's a lot going on in this Merlot, which i...",NaN,86,4.0,California,California,California Other,NaN,NaN,Bandit NV Merlot (California),Merlot,Bandit,21.50
126096,Romania,Notes of sun-dried hay and green flower highli...,UnWineD,86,4.0,Viile Timisului,NaN,NaN,Anna Lee C. Iijima,NaN,Cramele Recas 2011 UnWineD Pinot Grigio (Viile...,Pinot Grigio,Cramele Recas,21.50
20484,US,"Fruity, soft and rather sweet, this wine smell...",NaN,85,4.0,California,Clarksburg,Central Valley,Jim Gordon,@gordone_cellars,Dancing Coyote 2015 White (Clarksburg),White Blend,Dancing Coyote,21.25
1987,Spain,Berry and cherry aromas are surprisingly sturd...,Flirty Bird,85,4.0,Central Spain,Vino de la Tierra de Castilla,NaN,Michael Schachner,@wineschach,Felix Solis 2013 Flirty Bird Syrah (Vino de la...,Syrah,Felix Solis,21.25
110255,US,"A good everyday Merlot, dry and rich in tannin...",NaN,84,4.0,California,California,California Other,NaN,NaN,Bandit NV Merlot (California),Merlot,Bandit,21.00

In [23]:
# Is a wine more likely to be "tropical" or "fruity"?
# Create a `Series` counting how many times each of these words appears in the `description` column

def contains_me(string):

    if "tropical" in string:
        return 0
    elif "fruity" in string:
        return 1
        
reviews['counted_desc'] = reviews['description'].apply(contains_me)

reviews['counted_desc'].value_counts()

1.0    8880
0.0    3607
Name: counted_desc, dtype: int64

In [24]:
#What combination of countries and varieties are most common?

reviews_4 = reviews[pd.notnull(reviews['country'])]
reviews_4 = reviews[pd.notnull(reviews['variety'])]

reviews_4['variations'] = reviews_4['country'] + " " + reviews_4['variety']
reviews_4['variations'].value_counts().head(5)

/Users/shaynahowitt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

US Pinot Noir                      9885
US Cabernet Sauvignon              7315
US Chardonnay                      6801
France Bordeaux-style Red Blend    4725
Italy Red Blend                    3624
Name: variations, dtype: int64

**Grouping and Sorting**

In [25]:
reviews['taster_twitter_handle'].value_counts()

@vossroger          25514
@wineschach         15134
@kerinokeefe        10776
@vboone              9537
@paulgwine           9532
@mattkettmann        6332
@JoeCz               5147
@wawinereport        4966
@gordone_cellars     4177
@AnneInVino          3685
@laurbuzz            1835
@suskostrzewa        1085
@worldwineguys       1005
@bkfiona               27
@winewchristina         6
Name: taster_twitter_handle, dtype: int64

In [26]:
#What is the best wine I can buy for a given amount of money? Create a Series whose index is wine prices and whose 
#values is the maximum number of points a wine costing that much was given in a review. Sort the valeus by price, 
#ascending (so that 4.0 dollars is at the top and 3300.0 dollars is at the bottom)

reviews.groupby('price').points.max().sort_index()

price
4.0        86
5.0        87
6.0        88
7.0        91
8.0        91
9.0        91
10.0       91
11.0       92
12.0       93
13.0       94
14.0       94
15.0       93
16.0       94
17.0       93
18.0       94
19.0       94
20.0       96
21.0       94
22.0       95
23.0       94
24.0       95
25.0       95
26.0       95
27.0       96
28.0       96
29.0       96
30.0       96
31.0       95
32.0       96
33.0       94
         ...
698.0      97
710.0      95
750.0      92
757.0      98
764.0      94
767.0      96
770.0      96
775.0      98
780.0      91
790.0      87
800.0      99
820.0      96
848.0     100
850.0      99
886.0      97
900.0      94
932.0      97
973.0      95
980.0      94
1000.0     97
1100.0     97
1125.0     94
1200.0     96
1300.0     96
1500.0    100
1900.0     98
2000.0     97
2013.0     91
2500.0     96
3300.0     88
Name: points, Length: 390, dtype: int64

In [27]:
#What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is 
#the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

max_variety = reviews.groupby('variety').points.max().sort_index()
min_variety = reviews.groupby('variety').points.min().sort_index()

min_variety2 = pd.DataFrame(min_variety).reset_index()
max_variety2 = pd.DataFrame(max_variety).reset_index()

min_max = pd.merge(min_variety2, max_variety2, on= 'variety')
min_max = min_max.rename(columns = {'points_x': 'minimum', 'points_y': 'maximum'})
min_max = min_max.set_index('variety')
min_max.head()

             minimum  maximum
variety
Abouriou          85       91
Agiorgitiko       83       92
Aglianico         81       97
Aidani            82       82
Airen             80       83

In [28]:
#Are there significant differences in the average scores assigned by the various reviewers? 
#Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer

reviews.groupby('taster_name').points.mean().sort_values()

taster_name
Alexander Peartree    85.855422
Carrie Dykes          86.395683
Susan Kostrzewa       86.609217
Fiona Adams           86.888889
Michael Schachner     86.907493
Lauren Buzzeo         87.739510
Christina Pickard     87.833333
Jeff Jenssen          88.319756
Anna Lee C. Iijima    88.415629
Joe Czerwinski        88.536235
Jim Gordon            88.626287
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Kerin O’Keefe         88.867947
Paul Gregutt          89.082564
Mike DeSimone         89.101167
Virginie Boone        89.213379
Matt Kettmann         90.008686
Anne Krebiehl MW      90.562551
Name: points, dtype: float64

In [29]:
#What are the most expensive wine varieties? 
#Sort in descending order based on `min` first, `max` second.

min_max.sort_values(['minimum', 'maximum'], ascending = False).head()

                     minimum  maximum
variety
Gelber Traminer           95       95
Terrantez                 95       95
Tinta del Pais            94       96
Riesling-Chardonnay       94       94
Sercial                   94       94

In [30]:
#What combination of countries and varieties are most common? 

reviews['count'] = 1
reviews['combined'] = reviews['country'] + " " + reviews['variety']

review7 = reviews.copy()
review7 = review7.groupby('combined').sum()
review7.sort_values('count', ascending = False).head(10)

                                 points     price  counted_desc  count
combined
US Pinot Noir                    885774  439530.0         361.0   9885
US Cabernet Sauvignon            651220  398863.0         250.0   7315
US Chardonnay                    601505  207507.0         217.0   6801
France Bordeaux-style Red Blend  419681  129764.0         740.0   4725
Italy Red Blend                  321812  129494.0          74.0   3624
US Syrah                         290116  125775.0         118.0   3244
US Red Blend                     261093   99206.0         188.0   2972
France Chardonnay                250645  127724.0         455.0   2808
Italy Nebbiolo                   247076  150503.0           7.0   2736
US Zinfandel                     238102   79777.0         180.0   2711

**Data Types and Missing Data**

In [31]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
counted_desc             float64
count                      int64
combined                  object
dtype: object

In [32]:
#Create a `Series` from entries in the `price` column, but convert the entries to strings.

def convert_me(x):
    return str(x)

reviews['price_strings'] = reviews['price'].apply(convert_me)

In [33]:
#Some wines do not list a price. How often does this occur? Generate a `Series`that, 
#for each review in the dataset, states whether the wine reviewed has a null `price`.

reviews['price'].isnull()

0          True
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13         True
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
129941    False
129942    False
129943    False
129944    False
129945    False
129946    False
129947    False
129948    False
129949    False
129950    False
129951    False
129952    False
129953    False
129954    False
129955    False
129956    False
129957    False
129958    False
129959    False
129960    False
129961    False
129962    False
129963    False
129964     True
129965    False
129966    False
129967    False
129968    False
129969    False
129970    False
Name: price, Length: 129971, dtype: bool

In [34]:
#What are the most common wine-producing regions? Create a `Series` counting the number of times each 
#value occurs in the `region_1` field. This field is often missing data, so replace missing values with 
#`Unknown`. Sort in descending order.  Your output should look something like this:

reviews['region1'] = reviews['region_1'].fillna('Unknown')
reviews['region1'].value_counts().head(3)

Unknown                 21247
Napa Valley              4480
Columbia Valley (WA)     4124
Name: region1, dtype: int64

In [35]:
#show how many times each of the columns in the dataset contains null values

reviews.isnull().sum()

country                      63
description                   0
designation               37465
points                        0
price                      8996
province                     63
region_1                  21247
region_2                  79460
taster_name               26244
taster_twitter_handle     31213
title                         0
variety                       1
winery                        0
counted_desc             117484
count                         0
combined                     64
price_strings                 0
region1                       0
dtype: int64

**Renaming and Combining**

In [36]:
#rename region1 and region2, and index

reviews = reviews.rename(columns = {"region_1": "region", "region_2": "locale"})
reviews.index.name = "wines"

In [37]:
#Create a `DataFrame` of products mentioned on the gaming or movie subreddit.

gaming_products = pd.read_csv("gaming.csv")
gaming_products['subreddit'] = "r/gaming"
movie_products = pd.read_csv("movies.csv")
movie_products['subreddit'] = "r/movies"

combined_df = pd.concat([gaming_products, movie_products])
combined_df = combined_df.drop_duplicates(subset='name')
combined_df.head()

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3,r/gaming
2,CanaKit 5V 2.5A Raspberry Pi 3 Power Supply / ...,Electronics,https://www.amazon.com/CanaKit-Raspberry-Suppl...,7.0,3,r/gaming
3,Panasonic K-KJ17MCA4BA Advanced Individual Cel...,Electronics,https://www.amazon.com/Panasonic-Advanced-Indi...,29.0,2,r/gaming
4,Mayflash GameCube Controller Adapter for Wii U...,Electronics,https://www.amazon.com/GameCube-Controller-Ada...,24.0,2,r/gaming

**Method Chaining**

In [38]:
chess_games = pd.read_csv('games.csv')

In [39]:
chess_games.head(1)

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5

In [40]:
#find ratio of wins according to color

chess_games["winner"].value_counts() / len(chess_games)

white    0.498604
black    0.454033
draw     0.047363
Name: winner, dtype: float64

In [41]:
# lambda n: n.split(":")[0].split("|")[0].split("#")[0].strip()

#Use this function to parse the `opening_name` field and generate a `pandas` `Series` 
#counting how many times each of the "opening archetypes" gets used

chess_games['opening_name'] = chess_games['opening_name'].apply(lambda n: n.split(":")
        [0].split("|")[0].split("#")[0].strip()).value_counts()

In [42]:
#count how many times each white player mates, resigns, draws

chess_games['n'] = 0
chess_games.groupby(['white_id', 'victory_status'])['n'].count().reset_index().head()

              white_id victory_status  n
0              --jim--           mate  1
1  -l-_jedi_knight_-l-           mate  1
2  -l-_jedi_knight_-l-      outoftime  1
3  -l-_jedi_knight_-l-         resign  4
4               -mati-         resign  1

In [43]:
#only track the top 20 players results

chess_games.groupby(['white_id', 'victory_status'])['n'].count().reset_index().pipe(lambda x: x.loc[x["white_id"].isin(chess_games["white_id"].value_counts().head(20).index)]).head()

         white_id victory_status   n
9      1240100948           draw   3
10     1240100948           mate   7
11     1240100948         resign  28
35  a_p_t_e_m_u_u           draw   5
36  a_p_t_e_m_u_u           mate  27

In [44]:
kepler = pd.read_csv("cumulative.csv")
kepler.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [45]:
kepler['n'] = 0
kepler.groupby(['koi_disposition', 'koi_pdisposition'])['n'].count().reset_index()

  koi_disposition koi_pdisposition     n
0       CANDIDATE        CANDIDATE  2248
1       CONFIRMED        CANDIDATE  2248
2       CONFIRMED   FALSE POSITIVE    45
3  FALSE POSITIVE   FALSE POSITIVE  5023